/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RolePermissionDTO } from './role-permission-dto';

/**
 * 
 * @export
 * @interface CreateRolePermissionDTO
 */
export interface CreateRolePermissionDTO {
    /**
     * Array of permissions
     * @type {Array<RolePermissionDTO>}
     * @memberof CreateRolePermissionDTO
     */
    'permissions': Array<RolePermissionDTO>;
}

