/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateJobAdvertDTO
 */
export interface CreateJobAdvertDTO {
    /**
     * About us for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_about_us'?: string;
    /**
     * What will you do for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_what_will_you_do'?: string;
    /**
     * What will you bring for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_what_you_will_bring'?: string;
    /**
     * What do we offer you for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_what_we_offer_you'?: string;
    /**
     * Key Indicators for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_key_indicators'?: string;
    /**
     * Job Advert Posting Type for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_job_posting_type'?: CreateJobAdvertDTOExternalJobPostingTypeEnum;
    /**
     * Agency name for external job advert (required if posting type is Agency)
     * @type {Array<string>}
     * @memberof CreateJobAdvertDTO
     */
    'external_agencies'?: Array<string>;
    /**
     * Start date for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_start_date'?: string;
    /**
     * End date for external job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'external_end_date'?: string;
    /**
     * About us for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_about_us'?: string;
    /**
     * What will you do for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_what_will_you_do'?: string;
    /**
     * What will you bring for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_what_you_will_bring'?: string;
    /**
     * What do we offer you for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_what_we_offer_you'?: string;
    /**
     * Key Indicators for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_key_indicators'?: string;
    /**
     * Job Advert Posting Type for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_job_posting_type'?: CreateJobAdvertDTOInternalJobPostingTypeEnum;
    /**
     * Start date for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_start_date'?: string;
    /**
     * End date for internal job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'internal_end_date'?: string;
    /**
     * Boolean to check if it is same as external or not
     * @type {boolean}
     * @memberof CreateJobAdvertDTO
     */
    'same_as_external'?: boolean;
    /**
     * status of job advert
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'status'?: string;
    /**
     * Id of the job
     * @type {string}
     * @memberof CreateJobAdvertDTO
     */
    'job_id'?: string;
}

export const CreateJobAdvertDTOExternalJobPostingTypeEnum = {
    Internal: 'Internal',
    External: 'External',
    Confidential: 'Confidential',
    Agency: 'Agency'
} as const;

export type CreateJobAdvertDTOExternalJobPostingTypeEnum = typeof CreateJobAdvertDTOExternalJobPostingTypeEnum[keyof typeof CreateJobAdvertDTOExternalJobPostingTypeEnum];
export const CreateJobAdvertDTOInternalJobPostingTypeEnum = {
    Internal: 'Internal',
    External: 'External',
    Confidential: 'Confidential',
    Agency: 'Agency'
} as const;

export type CreateJobAdvertDTOInternalJobPostingTypeEnum = typeof CreateJobAdvertDTOInternalJobPostingTypeEnum[keyof typeof CreateJobAdvertDTOInternalJobPostingTypeEnum];


