/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUnitDTO
 */
export interface CreateUnitDTO {
    /**
     * Unique identifier for the platform
     * @type {string}
     * @memberof CreateUnitDTO
     */
    'platform_id': string;
    /**
     * Unique identifier for the user role
     * @type {string}
     * @memberof CreateUnitDTO
     */
    'user_role_id': string;
    /**
     * Name of the unit
     * @type {string}
     * @memberof CreateUnitDTO
     */
    'name': string;
}

