/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateJobAssociationDto } from './create-job-association-dto';

/**
 * 
 * @export
 * @interface CreateJobDto
 */
export interface CreateJobDto {
    /**
     * requisition / Job Title 
     * @type {string}
     * @memberof CreateJobDto
     */
    'job_title': string;
    /**
     * Grade of job
     * @type {string}
     * @memberof CreateJobDto
     */
    'grade': string;
    /**
     * Platform of the Job
     * @type {string}
     * @memberof CreateJobDto
     */
    'platform': string;
    /**
     * unit of the Job
     * @type {string}
     * @memberof CreateJobDto
     */
    'unit': string;
    /**
     * Location of the Job
     * @type {string}
     * @memberof CreateJobDto
     */
    'location': string;
    /**
     * 
     * @type {string}
     * @memberof CreateJobDto
     */
    'nationality': string;
    /**
     * 
     * @type {string}
     * @memberof CreateJobDto
     */
    'project_code': string;
    /**
     * 
     * @type {number}
     * @memberof CreateJobDto
     */
    'jr_number': number;
    /**
     * Number of hirings
     * @type {number}
     * @memberof CreateJobDto
     */
    'hiring_count': number;
    /**
     * contract type
     * @type {string}
     * @memberof CreateJobDto
     */
    'contract_type': string;
    /**
     * Type of Budget
     * @type {string}
     * @memberof CreateJobDto
     */
    'budget_type': string;
    /**
     * Year of Budget
     * @type {string}
     * @memberof CreateJobDto
     */
    'budget_year': string;
    /**
     * business case/ comments/ description
     * @type {string}
     * @memberof CreateJobDto
     */
    'business_case': string;
    /**
     * List of job associations
     * @type {Array<CreateJobAssociationDto>}
     * @memberof CreateJobDto
     */
    'jobAssociation': Array<CreateJobAssociationDto>;
}

