/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateRoleDTO
 */
export interface CreateRoleDTO {
    /**
     * The role name
     * @type {string}
     * @memberof CreateRoleDTO
     */
    'role_name': string;
    /**
     * The label of the role
     * @type {string}
     * @memberof CreateRoleDTO
     */
    'role_label': string;
    /**
     * The description of the role
     * @type {string}
     * @memberof CreateRoleDTO
     */
    'role_description': string;
}

