/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateJobAssociationDto
 */
export interface CreateJobAssociationDto {
    /**
     * User details who performed the action
     * @type {Array<string>}
     * @memberof CreateJobAssociationDto
     */
    'actionBy': Array<string>;
}

