/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAssessmentDTO
 */
export interface CreateAssessmentDTO {
    /**
     * Type of assessment (e.g., coding test)
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    'type': string;
    /**
     * Description of the assessment
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    'description': string;
    /**
     * Purpose of the assessment
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    'purpose': string;
    /**
     * Duration of the assessment in minutes
     * @type {number}
     * @memberof CreateAssessmentDTO
     */
    'duration': number;
    /**
     * Platform used for the assessment (e.g., HackerRank)
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    'platform': string;
    /**
     * Instructions for the assessment
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    'instructions': string;
    /**
     * Link to the assessment
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    'assessment_link': string;
    /**
     * Current status of the assessment (e.g., Pending, Completed)
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    'status': string;
}

