/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateQuestionDto
 */
export interface CreateQuestionDto {
    /**
     * The question text
     * @type {string}
     * @memberof CreateQuestionDto
     */
    'question': string;
    /**
     * Type of the question (e.g., radio, text)
     * @type {string}
     * @memberof CreateQuestionDto
     */
    'question_type': string;
    /**
     * Options for multiple choice questions
     * @type {Array<string>}
     * @memberof CreateQuestionDto
     */
    'options'?: Array<string>;
    /**
     * Question Tag (e.g., Leadership etc)
     * @type {string}
     * @memberof CreateQuestionDto
     */
    'question_tag': string;
    /**
     * Candidate type (e.g., Internal, External, Both)
     * @type {string}
     * @memberof CreateQuestionDto
     */
    'target_candidate': string;
    /**
     * Indicates if this is a preset question
     * @type {boolean}
     * @memberof CreateQuestionDto
     */
    'is_preset': boolean;
    /**
     * Indicates if the question is mandatory
     * @type {boolean}
     * @memberof CreateQuestionDto
     */
    'is_mandatory': boolean;
}

