/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MilestonesStepsDTO } from './milestones-steps-dto';

/**
 * 
 * @export
 * @interface CreateProjectMilestoneDTO
 */
export interface CreateProjectMilestoneDTO {
    /**
     * 
     * @type {MilestonesStepsDTO}
     * @memberof CreateProjectMilestoneDTO
     */
    'rap_send'?: MilestonesStepsDTO;
    /**
     * 
     * @type {MilestonesStepsDTO}
     * @memberof CreateProjectMilestoneDTO
     */
    'rap_approve'?: MilestonesStepsDTO;
    /**
     * 
     * @type {MilestonesStepsDTO}
     * @memberof CreateProjectMilestoneDTO
     */
    'shortlist_delivery'?: MilestonesStepsDTO;
    /**
     * 
     * @type {MilestonesStepsDTO}
     * @memberof CreateProjectMilestoneDTO
     */
    'assessment_complete'?: MilestonesStepsDTO;
    /**
     * 
     * @type {MilestonesStepsDTO}
     * @memberof CreateProjectMilestoneDTO
     */
    'hiring_decision'?: MilestonesStepsDTO;
    /**
     * 
     * @type {MilestonesStepsDTO}
     * @memberof CreateProjectMilestoneDTO
     */
    'offer_approved'?: MilestonesStepsDTO;
    /**
     * 
     * @type {MilestonesStepsDTO}
     * @memberof CreateProjectMilestoneDTO
     */
    'offer_accepted'?: MilestonesStepsDTO;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectMilestoneDTO
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectMilestoneDTO
     */
    'job_id': string;
    /**
     * status
     * @type {string}
     * @memberof CreateProjectMilestoneDTO
     */
    'status': string;
}

