/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResendOtpDTO
 */
export interface ResendOtpDTO {
    /**
     * Email of the user
     * @type {string}
     * @memberof ResendOtpDTO
     */
    'email': string;
}

