/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResetPasswordDTO
 */
export interface ResetPasswordDTO {
    /**
     * This is new password for user
     * @type {string}
     * @memberof ResetPasswordDTO
     */
    'new_password': string;
    /**
     * otp
     * @type {number}
     * @memberof ResetPasswordDTO
     */
    'otp': number;
}

