/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RolePermissionDTO
 */
export interface RolePermissionDTO {
    /**
     * The ID of the permission
     * @type {string}
     * @memberof RolePermissionDTO
     */
    'resource_id': string;
    /**
     * Indicates if the role has read permission
     * @type {boolean}
     * @memberof RolePermissionDTO
     */
    'can_read': boolean;
    /**
     * Indicates if the role has write permission
     * @type {boolean}
     * @memberof RolePermissionDTO
     */
    'can_write': boolean;
    /**
     * Indicates if the role has delete permission
     * @type {boolean}
     * @memberof RolePermissionDTO
     */
    'can_delete': boolean;
    /**
     * Indicates if the role has edit permission
     * @type {boolean}
     * @memberof RolePermissionDTO
     */
    'can_edit': boolean;
}

