/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateSettingDTO
 */
export interface UpdateSettingDTO {
    /**
     * The category of the setting
     * @type {string}
     * @memberof UpdateSettingDTO
     */
    'category': UpdateSettingDTOCategoryEnum;
    /**
     * Key of the field
     * @type {string}
     * @memberof UpdateSettingDTO
     */
    'key': string;
    /**
     * Value of the setting, can be string or JSON
     * @type {object}
     * @memberof UpdateSettingDTO
     */
    'value': object;
    /**
     * Type of the field
     * @type {string}
     * @memberof UpdateSettingDTO
     */
    'type': string;
    /**
     * Description of the setting
     * @type {string}
     * @memberof UpdateSettingDTO
     */
    'description': string;
}

export const UpdateSettingDTOCategoryEnum = {
    Theme: 'theme',
    System: 'system',
    Security: 'security',
    Notification: 'notification',
    Integration: 'integration',
    Performance: 'performance',
    Analytics: 'analytics',
    Payment: 'payment',
    Privacy: 'privacy'
} as const;

export type UpdateSettingDTOCategoryEnum = typeof UpdateSettingDTOCategoryEnum[keyof typeof UpdateSettingDTOCategoryEnum];


