/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateJobApplicationStatusDto
 */
export interface UpdateJobApplicationStatusDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateJobApplicationStatusDto
     */
    'new_status': UpdateJobApplicationStatusDtoNewStatusEnum;
    /**
     * Comment/Reason of rejected
     * @type {string}
     * @memberof UpdateJobApplicationStatusDto
     */
    'comment': string;
}

export const UpdateJobApplicationStatusDtoNewStatusEnum = {
    Applied: 'Applied',
    Prescreen: 'Prescreen',
    Shortlist: 'Shortlist',
    Assess: 'Assess',
    Offer: 'Offer',
    Contract: 'Contract',
    Started: 'Started'
} as const;

export type UpdateJobApplicationStatusDtoNewStatusEnum = typeof UpdateJobApplicationStatusDtoNewStatusEnum[keyof typeof UpdateJobApplicationStatusDtoNewStatusEnum];


