/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateMilestonesStepsDTO
 */
export interface UpdateMilestonesStepsDTO {
    /**
     * Person responsible for this step
     * @type {string}
     * @memberof UpdateMilestonesStepsDTO
     */
    'responsible_person'?: string;
    /**
     * Average cycle time for this step
     * @type {string}
     * @memberof UpdateMilestonesStepsDTO
     */
    'average_cycle_time'?: string;
    /**
     * Target date for completing this step
     * @type {string}
     * @memberof UpdateMilestonesStepsDTO
     */
    'target_date'?: string;
}

