/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePlatformDTO
 */
export interface UpdatePlatformDTO {
    /**
     * Name of the platform
     * @type {string}
     * @memberof UpdatePlatformDTO
     */
    'name': string;
    /**
     * Description of the platform
     * @type {string}
     * @memberof UpdatePlatformDTO
     */
    'description'?: string;
    /**
     * Type of platform (e.g., SaaS, PaaS)
     * @type {string}
     * @memberof UpdatePlatformDTO
     */
    'type'?: string;
}

