/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePermissionDto
 */
export interface UpdatePermissionDto {
    /**
     * Permission to read the resource
     * @type {boolean}
     * @memberof UpdatePermissionDto
     */
    'can_read': boolean;
    /**
     * Permission to write to the resource
     * @type {boolean}
     * @memberof UpdatePermissionDto
     */
    'can_write': boolean;
    /**
     * Permission to edit the resource
     * @type {boolean}
     * @memberof UpdatePermissionDto
     */
    'can_edit': boolean;
    /**
     * Permission to delete the resource
     * @type {boolean}
     * @memberof UpdatePermissionDto
     */
    'can_delete': boolean;
}

