/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateJobCategoryDTO
 */
export interface UpdateJobCategoryDTO {
    /**
     * The name of the category.
     * @type {string}
     * @memberof UpdateJobCategoryDTO
     */
    'name': string;
    /**
     * A brief description of the category.
     * @type {string}
     * @memberof UpdateJobCategoryDTO
     */
    'description': string;
}

