/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserRoleDTO
 */
export interface UpdateUserRoleDTO {
    /**
     * IDs of the roles
     * @type {Array<string>}
     * @memberof UpdateUserRoleDTO
     */
    'role_ids': Array<string>;
}

