/* tslint:disable */
/* eslint-disable */
/**
 * Takafo+
 * The Takafo API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateStatusDTO
 */
export interface UpdateStatusDTO {
    /**
     * Will active or deactivate setting
     * @type {boolean}
     * @memberof UpdateStatusDTO
     */
    'is_active': boolean;
}

