
name: Deploy Takafo frontend
on:
  push:
    branches:
      - cicd-test

jobs:
  build:        
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true  # Set to false if you want all jobs to run regardless of individual failures
      matrix:
        node-version: ['20.13.0'] # Test against multiple node versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # Use matrix node versiobn
      - name: Create .env file
        run: |
          echo VITE_APP_BACKEND_URL=https://az-takafo-stag.hcms.ai/v1 > .env

      - name: check environment file
        run: |
          cat .env
      
      - name: Install NPM dependencies
        run: |
          npx @nestjs/cli --version
          npm i
    
      - name: Build assets
        run: |
         npm run build

      - name: Upload to Azure Storage
        env:
          AZURE_CLIENT_ID: ${{ secrets.SP_TAKAFO_FRONTEND_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.SP_AKAFO_FRONTEND_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.SP_TAKAFO_FRONTEND_ENANT_ID }}
          AZURE_STORAGE_ACCOUNT: satestsite
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az storage blob upload-batch -d '$web' -s dist --account-name $AZURE_STORAGE_ACCOUNT --overwrite

      
